/** What DERIVE asks for, and the file it asks for it in. */
export const CHECKS_FILE = "checks.json";

export function brief(spec: string, appUrl: string, target: string): string {
  return [
    "Below is a specification for a web application that does not exist yet.",
    "Read it and state which of its claims a judge could verify by reading a",
    "value — from the mirror node, a route, or an element — with no judgement.",
    "",
    "You have three kinds available:",
    "",
    `- **dom** — what an element shows in a real browser. \`path\` is a route like`,
    "  `/send`, `field` is a CSS selector like `#send-error`. Prefer this for anything",
    "  the spec says a user sees: it waits for the page to render, so it works where",
    "  reading the raw HTML does not.",
    `- **http** — the app will run at ${appUrl}. \`path\` is a route, \`field\` is`,
    "  `status` or `body`. Use it for whether a route exists, not for what it shows.",
    "- **chain** — a read from the Hedera mirror node. `path` is below `/api/v1/`,",
    "  like `accounts/0.0.2`, and `field` is a dotted path such as `balance.balance`.",
    "  Use this only where the spec names a specific account, topic or contract.",
    "",
    "Rules that matter more than coverage:",
    "",
    "- **Only what the spec states plainly.** You are reading someone's words, not",
    "  guessing at an implementation. If a claim needs interpretation, leave it —",
    "  a human judge checks those, and a check that misreads prose fails an app",
    "  that is correct.",
    "- **Nothing that depends on what the run creates.** You cannot name an account",
    "  the app will make, a contract it will deploy, or a transaction it will send;",
    "  none of them exist yet. Those are checked later by someone who watched it happen.",
    "- **A dom check reads text, not state.** It gets what the element shows. A",
    "  spec saying a control is disabled, a field hidden, a row highlighted is",
    "  describing state, and matching the word `disabled` against `Send` fails an",
    "  app that is doing exactly what was asked.",
    "- **Nothing conditional.** \"Once a send completes the id appears\" and \"before",
    "  a send neither element exists\" each describe a moment. A check has no way to",
    "  know which moment it is looking at, so it asserts the condition always held.",
    "  Take only claims true whenever the app is up.",
    "- **Nothing vacuous.** `matches: \".*\"` and `contains: \"\"` hold against a blank",
    "  page. If you cannot say what would make it fail, it is not a check.",
    "- **Patterns are JavaScript.** The judge evaluates them in JavaScript — a",
    "  `node` one-liner or the browser console — which has no inline flags.",
    "  Write `[Nn]ot`, not `(?i)not`.",
    "- **Quote the phrase each check comes from.** A reader has to be able to see",
    "  whether you read it the way they meant it.",
    "- **An empty list is a fine answer.** Most specs are mostly judgement.",
    "",
    "--- the spec ---",
    spec,
    "--- end ---",
    "",
    `Write what you have to ${target}, as a JSON array and nothing else — no`,
    "prose around it, no markdown fence. Each entry:",
    "",
    "    {",
    '      "kind": "chain" | "http" | "dom",',
    '      "path": "accounts/0.0.2" | "/send",',
    '      "field": "balance.balance" | "status" | "body" | "#send-error",',
    '      "expect": { "equals": … } | { "matches": … } | { "contains": … } | { "atLeast": … },',
    '      "because": "the phrase in the spec this comes from, quoted"',
    "    }",
    "",
    "Exactly one key inside `expect`. An empty array `[]` is a fine answer, and",
    "a better one than a check you had to invent.",
  ].join("\n");
}
